# Generated by Django 2.2.1 on 2019-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190829_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='web_site',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
