# Generated by Django 2.2.1 on 2019-09-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ('-created_at',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
